name: Release Version

on:
  pull_request:
    types:
      - closed
    branches-ignore:
      - master
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        if: github.event.pull_request.merged == true
        uses: melheffe/version_release_composer@master
        env:
          PREPEND: 'v'
          APPEND: '.aws' # must include '.' or it will append without separation
          DRAFT: 'false'
          PRERELEASE: 'true'
          TOKEN: ${{ secrets.AUTH_TOKEN }}
          TRIGGER: ${{ github.event.pull_request.base.ref }} # can use the triggering branch or define a fixed one like this: 'master'
          REPO_OWNER: kipusystems
          VERSION_FILE_NAME: 'VERSION'
